version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on: 
      - hub
    environment: 
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on: 
      - hub
    environment:
      - HUB_HOST=hub
  search-module1:    
    image: vivek1334/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result1:/usr/share/udmey/test-output
  search-module2:    
    image: vivek1334/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result2:/usr/share/udmey/test-output
  book-flight-module1:    
    image: vivek1334/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result1:/usr/share/udmey/test-output
  book-flight-module2:    
    image: vivek1334/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result2:/usr/share/udmey/test-output
